spring:
  application:
    name: blog-search
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:blog-search
    driverClassName: org.h2.Driver
    username: ryan
    password: ryan
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true


kakao-daum:
  api:
    url: https://dapi.kakao.com
    key: 6adff3b55b6bb50e22b3ffde4117c401
